<?php

namespace App\Model;

use App\Model\Keyboard;

class AZERTYKeyboard extends Keyboard
{
    public function __construct()
    {
        $keys = [
            new KeyStats("²", [0.75, 0.75]),
            new KeyStats("&", [2.65, 0.75]),
            new KeyStats("é", [4.55, 0.75]),
            new KeyStats("\"", [6.45, 0.75]),
            new KeyStats("'", [8.35, 0.75]),
            new KeyStats("(", [10.25, 0.75]),
            new KeyStats("-", [12.15, 0.75]),
            new KeyStats("è", [14.05, 0.75]),
            new KeyStats("_", [15.95, 0.75]),
            new KeyStats("ç", [17.85, 0.75]),
            new KeyStats("à", [19.75, 0.75]),
            new KeyStats(")", [21.65, 0.75]),
            new KeyStats("=", [23.55, 0.75]),
            new KeyStats("Backspace", [26.25, 0.75]),
            new KeyStats("Tab", [1.25, 2.65]),
            new KeyStats("a", [3.7, 2.65]),
            new KeyStats("z", [5.6, 2.65]),
            new KeyStats("e", [7.5, 2.65]),
            new KeyStats("r", [9.4, 2.65]),
            new KeyStats("t", [11.3, 2.65]),
            new KeyStats("y", [13.2, 2.65]),
            new KeyStats("u", [15.1, 2.65]),
            new KeyStats("i", [17, 2.65]),
            new KeyStats("o", [18.9, 2.65]),
            new KeyStats("p", [20.8, 2.65]),
            new KeyStats("^", [22.7, 2.65]),
            new KeyStats("$", [24.6, 2.65]),
            new KeyStats("Enter", [27.1, 3.7]),
            new KeyStats("Verr Maj", [1.5, 4.55]),
            new KeyStats("q", [4.1, 4.55]),
            new KeyStats("s", [6, 4.55]),
            new KeyStats("d", [7.9, 4.55]),
            new KeyStats("f", [9.8, 4.55]),
            new KeyStats("g", [11.7, 4.55]),
            new KeyStats("h", [13.6, 4.55]),
            new KeyStats("j", [15.5, 4.55]),
            new KeyStats("k", [17.4, 4.55]),
            new KeyStats("l", [19.3, 4.55]),
            new KeyStats("m", [21.2, 4.55]),
            new KeyStats("ù", [23.1, 4.55]),
            new KeyStats("*", [25, 4.55]),
            new KeyStats("Maj2", [1, 6.45]),
            new KeyStats("<", [3.2, 6.45]),
            new KeyStats("w", [5.1, 6.45]),
            new KeyStats("x", [7, 6.45]),
            new KeyStats("c", [8.9, 6.45]),
            new KeyStats("v", [10.8, 6.45]),
            new KeyStats("b", [12.7, 6.45]),
            new KeyStats("n", [14.6, 6.45]),
            new KeyStats(",", [16.5, 6.45]),
            new KeyStats(";", [18.4, 6.45]),
            new KeyStats(":", [20.3, 6.45]),
            new KeyStats("!", [22.2, 6.45]),
            new KeyStats("Maj", [25.7, 6.45]),
            new KeyStats("Ctrl", [1, 8.35]),
            new KeyStats("Fn", [3.2, 8.35]),
            new KeyStats("Menu", [5.1, 8.35]),
            new KeyStats("Alt", [7, 8.35]),
            new KeyStats("Space", [13, 8.35]),
            new KeyStats("Alt Gr", [20.3, 8.35]),
            new KeyStats("Fn 2", [22.2, 8.35]),
        ];
        $characters = [
            //natural
            new Character("²",[$keys[0]]),
            new Character("&",[$keys[1]]),
            new Character("é",[$keys[2]]),
            new Character("\"",[$keys[3]]),
            new Character("'",[$keys[4]]),
            new Character("(",[$keys[5]]),
            new Character("-",[$keys[6]]),
            new Character("è",[$keys[7]]),
            new Character("_",[$keys[8]]),
            new Character("ç",[$keys[9]]),
            new Character("à",[$keys[10]]),
            new Character(")",[$keys[11]]),
            new Character("=",[$keys[12]]),
            new Character("a",[$keys[15]]),
            new Character("z",[$keys[16]]),
            new Character("e",[$keys[17]]),
            new Character("r",[$keys[18]]),
            new Character("t",[$keys[19]]),
            new Character("y",[$keys[20]]),
            new Character("u",[$keys[21]]),
            new Character("i",[$keys[22]]),
            new Character("o",[$keys[23]]),
            new Character("p",[$keys[24]]),
            new Character("^",[$keys[25]]),
            new Character("$",[$keys[26]]),
            new Character("q",[$keys[29]]),
            new Character("s",[$keys[30]]),
            new Character("d",[$keys[31]]),
            new Character("f",[$keys[32]]),
            new Character("g",[$keys[33]]),
            new Character("h",[$keys[34]]),
            new Character("j",[$keys[35]]),
            new Character("k",[$keys[36]]),
            new Character("l",[$keys[37]]),
            new Character("m",[$keys[38]]),
            new Character("ù",[$keys[39]]),
            new Character("*",[$keys[40]]),
            new Character("<",[$keys[42]]),
            new Character("w",[$keys[43]]),
            new Character("x",[$keys[44]]),
            new Character("c",[$keys[45]]),
            new Character("v",[$keys[46]]),
            new Character("b",[$keys[47]]),
            new Character("n",[$keys[48]]),
            new Character(",",[$keys[49]]),
            new Character(";",[$keys[50]]),
            new Character(":",[$keys[51]]),
            new Character("!",[$keys[52]]),
            new Character(" ",[$keys[58]]),
            new Character(PHP_EOL, [$keys[27]]),

            //Shift
            new Character("³",[$keys[0],$keys[53]]),
            new Character("1",[$keys[1],$keys[53]]),
            new Character("2",[$keys[2],$keys[53]]),
            new Character("3",[$keys[3],$keys[53]]),
            new Character("4",[$keys[4],$keys[53]]),
            new Character("5",[$keys[5],$keys[53]]),
            new Character("6",[$keys[6],$keys[53]]),
            new Character("7",[$keys[7],$keys[41]]),
            new Character("8",[$keys[8],$keys[41]]),
            new Character("9",[$keys[9],$keys[41]]),
            new Character("0",[$keys[10],$keys[41]]),
            new Character("°",[$keys[11],$keys[41]]),
            new Character("+",[$keys[12],$keys[41]]),
            new Character("A",[$keys[15],$keys[53]]),
            new Character("Z",[$keys[16],$keys[53]]),
            new Character("E",[$keys[17],$keys[53]]),
            new Character("R",[$keys[18],$keys[53]]),
            new Character("T",[$keys[19],$keys[53]]),
            new Character("Y",[$keys[20],$keys[53]]),
            new Character("U",[$keys[21],$keys[41]]),
            new Character("I",[$keys[22],$keys[41]]),
            new Character("O",[$keys[23],$keys[41]]),
            new Character("P",[$keys[24],$keys[41]]),
            new Character("¨",[$keys[25],$keys[41]]),
            new Character("£",[$keys[26],$keys[41]]),
            new Character("Q",[$keys[29],$keys[53]]),
            new Character("S",[$keys[30],$keys[53]]),
            new Character("D",[$keys[31],$keys[53]]),
            new Character("F",[$keys[32],$keys[53]]),
            new Character("G",[$keys[33],$keys[53]]),
            new Character("H",[$keys[34],$keys[41]]),
            new Character("J",[$keys[35],$keys[41]]),
            new Character("K",[$keys[36],$keys[41]]),
            new Character("L",[$keys[37],$keys[41]]),
            new Character("M",[$keys[38],$keys[41]]),
            new Character("%",[$keys[39],$keys[41]]),
            new Character("µ",[$keys[40],$keys[41]]),
            new Character(">",[$keys[42],$keys[53]]),
            new Character("W",[$keys[43],$keys[53]]),
            new Character("X",[$keys[44],$keys[53]]),
            new Character("C",[$keys[45],$keys[53]]),
            new Character("V",[$keys[46],$keys[53]]),
            new Character("B",[$keys[47],$keys[53]]),
            new Character("N",[$keys[48],$keys[41]]),
            new Character("?",[$keys[49],$keys[41]]),
            new Character(".",[$keys[50],$keys[41]]),
            new Character("/",[$keys[51],$keys[41]]),
            new Character("§",[$keys[52],$keys[41]]),

            //Alt Gr
            new Character("¹",[$keys[0],$keys[59]]),
            new Character("ˇ",[$keys[1],$keys[59]]),
            new Character("~",[$keys[2],$keys[59]]),
            new Character("#",[$keys[3],$keys[59]]),
            new Character("{",[$keys[4],$keys[59]]),
            new Character("[",[$keys[5],$keys[59]]),
            new Character("|",[$keys[6],$keys[59]]),
            new Character("`",[$keys[7],$keys[59]]),
            new Character("\\",[$keys[8],$keys[59]]),
            new Character("@",[$keys[10],$keys[59]]),
            new Character("]",[$keys[11],$keys[59]]),
            new Character("}",[$keys[12],$keys[59]]),
            new Character("æ",[$keys[15],$keys[59]]),
            new Character("â",[$keys[16],$keys[59]]),
            new Character("€",[$keys[17],$keys[59]]),
            new Character("ê",[$keys[18],$keys[59]]),
            new Character("þ",[$keys[19],$keys[59]]),
            new Character("ÿ",[$keys[20],$keys[59]]),
            new Character("û",[$keys[21],$keys[59]]),
            new Character("î",[$keys[22],$keys[59]]),
            new Character("œ",[$keys[23],$keys[59]]),
            new Character("ô",[$keys[24],$keys[59]]),
            new Character("ø",[$keys[26],$keys[59]]),
            new Character("ä",[$keys[29],$keys[59]]),
            new Character("ß",[$keys[30],$keys[59]]),
            new Character("ë",[$keys[31],$keys[59]]),
            new Character("‘",[$keys[32],$keys[59]]),
            new Character("’",[$keys[33],$keys[59]]),
            new Character("ð",[$keys[34],$keys[59]]),
            new Character("ü",[$keys[35],$keys[59]]),
            new Character("ï",[$keys[36],$keys[59]]),
            new Character("ŀ",[$keys[37],$keys[59]]),
            new Character("ö",[$keys[38],$keys[59]]),
            new Character("≤",[$keys[42],$keys[59]]),
            new Character("«",[$keys[43],$keys[59]]),
            new Character("»",[$keys[44],$keys[59]]),
            new Character("©",[$keys[45],$keys[59]]),
            new Character("↓",[$keys[47],$keys[59]]),
            new Character("¬",[$keys[48],$keys[59]]),
            new Character("¿",[$keys[49],$keys[59]]),
            new Character("×",[$keys[50],$keys[59]]),
            new Character("÷",[$keys[51],$keys[59]]),
            new Character("¡",[$keys[52],$keys[59]]),
        ];

        $fingers = [
            new Finger("Left little", $keys[29], [$keys[0],$keys[1],$keys[15],$keys[29],$keys[43],$keys[42],$keys[41],$keys[14],$keys[28]]),
            new Finger("Left ring", $keys[30], [$keys[2],$keys[16],$keys[30],$keys[44]]),
            new Finger("Left middle", $keys[31], [$keys[3],$keys[17],$keys[31],$keys[45]]),
            new Finger("Left index", $keys[32], [$keys[4],$keys[5],$keys[18],$keys[19],$keys[32],$keys[33],$keys[46],$keys[47]]),
            new Finger("Left thumb", $keys[58], [$keys[58]]),
            new Finger("Right thumb", $keys[58], [$keys[58],$keys[59]]),
            new Finger("Right index", $keys[35], [$keys[6],$keys[7],$keys[20],$keys[21],$keys[34],$keys[35],$keys[48],$keys[49]]),
            new Finger("Right middle", $keys[36], [$keys[8],$keys[22],$keys[36],$keys[50]]),
            new Finger("Right ring", $keys[37], [$keys[9],$keys[23],$keys[37],$keys[51]]),
            new Finger("Right little", $keys[38], [$keys[10],$keys[11],$keys[12],$keys[13],$keys[24],$keys[25],$keys[26],$keys[27],$keys[38],$keys[39],$keys[40],$keys[52],$keys[53]])
        ];

        parent::__construct($keys, $characters, $fingers);
    }
}